<?php

/*
 * Copyright 2013 Gonzalo Moreno <goncab380@hotmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Trackme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends EntityRepository
{
    public function getLastBusiness()
    {
        $first_day_month = date('m', strtotime("first day of this month midnight"));
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT b
            FROM TrackmeBackendBundle:Business b
            WHERE b.created_at > :first_day_month');
        $query->setParameter('first_day_month', $first_day_month);

        return $query->getArrayResult();
    }

    public function getLastOt($business, $limit)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT o
            FROM TrackmeBackendBundle:Ot o
            LEFT JOIN o.
            LEFT JOIN o.user u
            LEFT JOIN u.business b
            WHERE b.id = :business
            ORDER BY o.id DESC')->setMaxResults($limit);
        $query->setParameter('business', $business->getId());

        return $query->getArrayResult();

    }

}
