<?php

namespace Trackme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoordinateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinateRepository extends EntityRepository
{
	public function getActiveVehicles($business)
	{
		$em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT c
            FROM TrackmeBackendBundle:Coordinate c 
            LEFT JOIN c.user u');
        // $query->setParameter('zone', $zone);

        return $query->getArrayResult();
	}
}
