<?php

/*
 * This file is part of the TrackmeBackendBundle package.
 *
 * (c) Gonzalo Moreno C. <goncab380@hotmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trackme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getActualOt($user)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT o
            FROM TrackmeBackendBundle:Ot o
            WHERE o.user > :user AND o.date_end IS NULL');
        $query->setParameter('user', $user);

        return $query->getSingleResult();
    }
}
