<?php
$I = new ApiGuy($scenario);
$I->wantTo('Enviar coordenadas de posicion en formato incorrecto');
$I->amHttpAuthenticated('api', 'api');
$I->haveHttpHeader("Content-Type", "application/json");
$I->sendPost('/position', array("tal" => -39, "gnl" => 39));
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'bad request'));
$I->seeResponseCodeIs(400);
$I->wantTo('Enviar coordenadas de posicion sin los parametros necesarios');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/position');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'bad request'));
$I->seeResponseCodeIs(400);
$I->wantTo('Enviar coordenadas de posicion y que la latitud no sea valida');
$I->amHttpAuthenticated('api', 'api');
$I->haveHttpHeader("Content-Type", "application/json");
$I->sendPost('/position', array("lat" => -91, "lng" => 179));
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'Latitud debe ser entre -90 y 90 grados'));
$I->seeResponseCodeIs(400);
$I->wantTo('Enviar coordenadas de posicion y que la longitud no sea valida');
$I->amHttpAuthenticated('api', 'api');
$I->haveHttpHeader("Content-Type", "application/json");
$I->sendPost('/position', array("lat" => -89, "lng" => 181));
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'Longitud debe ser entre -180 y 180 grados'));
$I->seeResponseCodeIs(400);