<?php
$I = new ApiGuy($scenario);
$I->wantTo('Realizar las operaciones comunes que se puedan dar en una OT');
$I->amGoingTo('Finalizar cualquier ot que exista');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->amGoingTo('Iniciar una ot');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/start');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ok'));
$I->seeResponseCodeIs(200);
$I->amGoingTo('Iniciar una ot (teniendo una ot activa)');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/start');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ot active'));
$I->seeResponseCodeIs(200);
$I->amGoingTo('Terminar una ot (teniendo ot activa)');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ok'));
$I->seeResponseCodeIs(200);
$I->amGoingTo('Terminar una ot (sin ot activa)');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'sin ot activa'));
$I->seeResponseCodeIs(200);
$I->amGoingTo('Enviar una peticion GET a la api start');
$I->amHttpAuthenticated('api', 'api');
$I->sendGet('/start');
$I->seeResponseCodeIs(405);
$I->amGoingTo('Enviar una peticion GET a la api finish');
$I->amHttpAuthenticated('api', 'api');
$I->sendGet('/finish');
$I->seeResponseCodeIs(405);
