<?php
$I = new ApiGuy($scenario);
$I->wantTo('Realizar las operaciones comunes que se puedan dar en una OT');
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/start');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ok'));
$I->seeResponseCodeIs(200);
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/start');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ot active'));
$I->seeResponseCodeIs(200);
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'ok'));
$I->seeResponseCodeIs(200);
$I->amHttpAuthenticated('api', 'api');
$I->sendPost('/finish');
$I->seeResponseIsJson();
$I->seeResponseContainsJson(array('status' => 'sin ot activa'));
$I->seeResponseCodeIs(200);
$I->amHttpAuthenticated('api', 'api');
$I->sendGet('/start');
$I->seeResponseCodeIs(405);
$I->amHttpAuthenticated('api', 'api');
$I->sendGet('/finish');
$I->seeResponseCodeIs(405);
