<?php
$I = new WebGuy($scenario);
$I->wantTo('Registrarme como empresa');
$I->amOnPage('/');
$I->see('Registro');
$I->click('Registro');
$I->amOnPage('/pricing');
$I->see('Escoja su Plan');
$I->click("#Business");
$I->amGoingTo('Llenar el formulario empresa');
$I->see('Empresa');
$I->fillField('#form_name', 'empresa falsa');
$I->fillField('#form_email', 'email@empresa.cl');
$I->fillField('#form_phone', '987978878');
$I->fillField('#form_address', 'almirante barroso 87, santiago');
$I->click('Aceptar');
$I->amGoingTo('Llenar el formulario de usuario');
$I->see('Usuario');
$I->fillField('#fos_user_registration_form_username', 'first_user');
$I->fillField('#fos_user_registration_form_email', 'petruxx@gmail.com');
$I->fillField('#fos_user_registration_form_plainPassword_first', '1234');
$I->fillField('#fos_user_registration_form_plainPassword_second', '1234');
$I->click('Registrar');
$I->amOnPage('/register/check-email');
// $I->see('Se ha enviado un email a petruxx@gmail.com.');
