imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

bazinga_geocoder:
    fake_ip: 190.22.206.10

raul_fraile_ladybug:
    general:
        expanded:             false
    object:
        max_nesting_level:    3

bazinga_faker:
    orm: doctrine
    entities:
        Trackme\BackendBundle\Entity\Business:
            number: 30
            custom_formatters:
                name: { method: company}
                email: { method: companyEmail}
                token: { method: uuid }
                created_by: { method: lastname}
                updated_by: { method: lastname}
#        Trackme\BackendBundle\Entity\User:
#            number: 90
        Trackme\BackendBundle\Entity\Vehicle:
            number: 90    
            custom_formatters:
                manufacturer: { method: company}
                model: { method: word}    

#swiftmailer:
#    delivery_address: me@example.com
