admin_review:
    resource: "@TrackmeBackendBundle/Controller/Review/"
    type:     admingenerator
    prefix:   /admin/business/review

index_api:
    path: /api
    defaults:  { _controller: TrackmeApiBundle:Default:index, _format: json }
    requirements: { _format: (xml|json), _method: POST }

trackme_api:
    resource: "@TrackmeApiBundle/Controller/"
    type:     annotation
    prefix:   /

admin_user:
    resource: "@TrackmeBackendBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/business/user

admin_business:
    resource: "@TrackmeBackendBundle/Controller/Business/"
    type:     admingenerator
    prefix:   /admin/cms/business

signup_user:
    path: /signup_user
    defaults:  { _controller: TrackmeFrontendBundle:Default:signupuser }    
    
signup:
    path: /signup
    defaults:  { _controller: TrackmeFrontendBundle:Default:signup }

page:
    path: /cms/{url}
    defaults:  { _controller: TrackmeFrontendBundle:Default:page }

admin_page:
    resource: "@TrackmeBackendBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /admin/cms/page

homepage:
    path: /
    defaults:  { _controller: TrackmeFrontendBundle:Default:index }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
