admin_ot:
    resource: "@TrackmeBackendBundle/Controller/Ot/"
    type:     admingenerator
    prefix:   /admin/business/ot

business_profile:
    pattern:      /admin/business/profile
    defaults:  { _controller: TrackmeBackendBundle:Default:profile }

uf:
    pattern:      /uf
    defaults:     { _controller: trackme.payment.controller:ufAction }

admin_global_payments:
    path: /admin/business/global-payments
    defaults:  { _controller: TrackmeBackendBundle:Payment:list }

admin_business_payments:
    path: /admin/business/payments
    defaults:  { _controller: TrackmeBackendBundle:Payment:businessList }

admin_business_details_payment:
    path: /admin/business/payments/{id}
    defaults:  { _controller: TrackmeBackendBundle:Payment:details }

admin_business_complete_payment:
    path: /admin/business/complete-payments/{id}
    defaults:  { _controller: TrackmeBackendBundle:Payment:complete }

admin_subscription:
    resource: "@TrackmeBackendBundle/Controller/Subscription/"
    type:     admingenerator
    prefix:   /admin/business/subscription

trackme_mobile:
    resource: "@TrackmeMobileBundle/Controller/"
    type:     annotation
    prefix:   /admin/mobile

dashboard_admin:
    path: /admin/dashboard
    defaults:  { _controller: TrackmeBackendBundle:Default:dashboard_admin }

admin_ticket:
    resource: "@TrackmeBackendBundle/Controller/Ticket/"
    type:     admingenerator
    prefix:   /admin/business/ticket

admin_mantention:
    resource: "@TrackmeBackendBundle/Controller/Mantention/"
    type:     admingenerator
    prefix:   /admin/business/mantention

admin_plan:
    resource: "@TrackmeBackendBundle/Controller/Plan/"
    type:     admingenerator
    prefix:   /admin/cms/plan

admin_vehicle:
    resource: "@TrackmeBackendBundle/Controller/Vehicle/"
    type:     admingenerator
    prefix:   /admin/business/vehicle

admin_map_dashboard:
    path: /admin/business/dashboard
    defaults:  { _controller: TrackmeBackendBundle:Default:dashboard }

login_api:
    path: /api/login
    defaults:  { _controller: TrackmeApiBundle:Default:login }
    options:
        expose: true

index_api:
    path: /api/position
    defaults:  { _controller: TrackmeApiBundle:Default:index, _format: json }
    requirements: { _format: (xml|json), _method: POST }
    options:
        expose: true

start:
    path: /api/start
    defaults:  { _controller: TrackmeApiBundle:Default:start, _format: json }
    requirements: { _format: (xml|json), _method: POST }
    options:
        expose: true  

finish:
    path: /api/finish
    defaults:  { _controller: TrackmeApiBundle:Default:finish, _format: json }
    requirements: { _format: (xml|json), _method: POST }
    options:
        expose: true                

trackme_api:
    resource: "@TrackmeApiBundle/Controller/"
    type:     annotation
    prefix:   /

admin_user:
    resource: "@TrackmeBackendBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/business/user

admin_business:
    resource: "@TrackmeBackendBundle/Controller/Business/"
    type:     admingenerator
    prefix:   /admin/cms/business

pricing:
    path: /pricing
    defaults:  { _controller: TrackmeFrontendBundle:Default:pricing }

signup_user:
    path: /signup_user
    defaults:  { _controller: TrackmeFrontendBundle:Default:signupuser }

create_business:
    path: /create_business
    defaults:  { _controller: TrackmeFrontendBundle:Default:create }

signup:
    path: /signup
    defaults:  { _controller: TrackmeFrontendBundle:Default:signup }

page:
    path: /cms/{url}
    defaults:  { _controller: TrackmeFrontendBundle:Default:page }

admin_page:
    resource: "@TrackmeBackendBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /admin/cms/page

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/cms/group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

homepage:
    path: /{path}
    defaults:  { _controller: TrackmeFrontendBundle:Default:index }

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true