Trackme\BackendBundle\Entity\ImageSlide:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
        path:
            type: string
        alt:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
