Trackme\BackendBundle\Entity\Media:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            nullable: true
        file:
            type: string
            length: 255
        alt:
            type: string
            length: 255
        enabled:
            type: boolean
    lifecycleCallbacks: {  }
