Trackme\BackendBundle\Entity\Plan:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
        featured:
            type: boolean
            default: false
        price:
            type: decimal
            precision: 10
            scale: 6
    lifecycleCallbacks: {  }
