Trackme\BackendBundle\Entity\PlanAttribute:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        value:
            type: string
            length: 255
        order: 
            type: integer
            required: false
        enabled:
            type: boolean
            default: true
    manyToOne:
        plan:
            targetEntity: Trackme\BackendBundle\Entity\Plan
            inversedBy: attributes
            joinColumn:
                name: plan_id
                referencedColumnName: id        
    lifecycleCallbacks: {  }
