Trackme\BackendBundle\Entity\Review:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        comment:
            type: text
        approved:
            type: boolean
            default: false
    manyToOne:
      business:
        targetEntity: Trackme\BackendBundle\Entity\Business
        joinColumn:
          onDelete: CASCADE
          name: business_id
          referencedColumnName: id        
    lifecycleCallbacks: {  }
