Trackme\BackendBundle\Entity\Ticket:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        type:
            type: string
            length: 255
        description:
            type: text
    manyToOne:
        user:
            targetEntity: Trackme\BackendBundle\Entity\User
            joinColumn:
                onDelete: CASCADE
                name: user_id
                referencedColumnName: id 
        state:
            targetEntity: Trackme\BackendBundle\Entity\TicketState
            joinColumn:
                onDelete: CASCADE
                name: state_id
                referencedColumnName: id        
    lifecycleCallbacks: {  }
