Trackme\BackendBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Trackme\BackendBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
      business:
        targetEntity: Trackme\BackendBundle\Entity\Business
        joinColumn:
          name: business_id
          referencedColumnName: id
    lifecycleCallbacks: {  }
