Trackme\BackendBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Trackme\BackendBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            required: true
        last_name:
            type: string
            length: 255
            required: true
        emailable:
            type: boolean
            default: true
    manyToOne:
      business:
        targetEntity: Trackme\BackendBundle\Entity\Business
        joinColumn:
          onDelete: CASCADE
          name: business_id
          referencedColumnName: id
    lifecycleCallbacks: {  }
