Trackme\BackendBundle\Entity\Vehicle:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        manufacturer:
            type: string
            length: 255
        model:
            type: string
            length: 255
        code:
            type: string
            length: 255
            unique: true
        type:
            type: string
            length: 255
        kilometerPerLiter:
            type: decimal
            precision: 10
            scale: 6
            column: kilometer_per_liter
    oneToMany:
        issues:
            targetEntity: Trackme\BackendBundle\Entity\VehicleMantention
            mappedBy: vehicle
            cascade: ["all"]
    manyToOne:
        business:
            targetEntity: Trackme\BackendBundle\Entity\Business
            joinColumn:
                onDelete: CASCADE
                name: business_id
                referencedColumnName: id        
    lifecycleCallbacks: {  }
