Trackme\BackendBundle\Entity\VehicleMantention:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateFrom:
            type: date
            column: date_from
        dateTo:
            type: date
            column: date_to
            nullable: true
        problem:
            type: text
            nullable: true
        solution:
            type: text
            nullable: true
        fixed:
            type: boolean
            nullable: true
        moreInfo:
            type: text
            column: more_info
            nullable: true
    manyToOne:
        vehicle:
            targetEntity: Trackme\BackendBundle\Entity\Vehicle
            inversedBy: issues
            joinColumn:
                name: vehicle_id
                referencedColumnName: id        
    lifecycleCallbacks: {  }
