generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Business
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields:
        name:
            label: Nombre
        phone:
            label: Teléfono
        enabled:
            label: Habilitado
builders:
    list:
        params:
            scopes:
                group_1:
                    Todos: ~
                    Deshabilitados:
                        filters:
                            enabled: false
                    Habilitados:
                        default: true
                        filters:
                            enabled: true
            title: Clientes
            display: [name,email,phone,enabled]
            actions:
                new: ~
            object_actions:
                show: ~
                delete: ~
    filters:
        params:
            display: [name, email, phone]
    new:
        params:
            title: Nuevo cliente (empresa)
            display: [name, email, phone]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando cliente \"%object%\"|{ %object%: Business.name }|"
            display: [name, email, phone]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo cliente \"%object%\"|{ %object%: Business.name }|"
            display: [name,email,phone,enabled]
            actions:
                list: ~
                new: ~
    delete: ~
