generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Plan
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields:
        name:
            label: Nombre
        featured:
            label: Recomendado
            help: Solo un plan debe ser seleccionado como recomendado
        refresh_time:
            label: Tiempo de refresco
            help: El envio de las coordenadas esta dada por los segundos.
        price:
            label: Precio
            addFormOptions:
                precision: 2
                attr:
                    placeholder: Valor en UF
        description:
            label: Descripcion
            addFormOptions:
              attr:
                class: tinymce

builders:
    list:
        params:
            title: Planes
            display: [ name, featured, price ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            title: Nuevo plan
            display: [ name, price, refresh_time, featured, description ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando plan \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, refresh_time, featured, description ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo plan \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, refresh_time, featured, description ]
            actions:
                list: ~
                new: ~
    delete: ~
