generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Plan
    namespace_prefix: Trackme
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: BackendBundle
    pk_requirement: ~
    fields:
        name:
            label: Nombre
        featured:
            label: Recomendado
            help: Solo un plan debe ser seleccionado como recomendado
        refresh_time:
            label: Tiempo de refresco
            help: El envio de las coordenadas esta dada por los segundos.
        users_limit:
            label: Cantidad maxima de usuarios
        price:
            label: Precio
            addFormOptions:
                precision: 2
                attr:
                    placeholder: Valor en UF
        description:
            label: Descripcion
            addFormOptions:
              attr:
                class: tinymce
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            title: Planes
            display: [ name, featured, price, users_limit ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            title: Nuevo plan
            display: [ name, price, refresh_time, users_limit, featured, description ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            title: "Editando plan \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, refresh_time, users_limit, featured, description ]
            actions:
                save: ~
                list: ~
    show:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            title: "Viendo plan \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, refresh_time, users_limit, featured, description ]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
