generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Plan
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields: 
        name:
            label: Nombre
        featured:
            label: Recomendado
            help: Solo un plan debe ser seleccionado como recomendado
        price:
            label: Precio
            formType: number
            addFormOptions:
                precision: 2
                attr:
                    placeholder: Valor en UF
        description:
            label: Descripcion
            addFormOptions:
              attr:
                class: tinymce boxsizingBorder

builders:
    list:
        params:
            title: Planes
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            title: Nuevo plan
            display: [ name, price, featured, description ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, featured, description ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo \"%object%\"|{ %object%: Plan.name }|"
            display: [ name, price, featured, description ]
            actions:
                list: ~
                new: ~
    delete: ~
