generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Review
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields: ~

builders:
    list:
        params:
            title: List for BackendBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            title: New object for BackendBundle
            display: [ comment]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object "
            display: [ comment, approved]
            fields:
                approved:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
