generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Review
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields:
        comment:
            label: Comentario

builders:
    list:
        params:
            title: Reseñas
            display: [ comment, business ]
            fields:
                business:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                new: ~
            object_actions:
                edit:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
                delete: ~
    filters:
        params:
            display: []
    new:
        params:
            title: Nueva Reseña
            display: [ comment ]
            actions:
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la reseña"
            display: [ business, comment, approved]
            fields:
                business:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
                approved:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
