generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Ticket
    namespace_prefix: Trackme
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: BackendBundle
    pk_requirement: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
    fields:
        title:
            label: Titulo
        description:
            label: Descripción
        state:
            label: Estado
        user:
            label: Usuario        
        type:
            formType: choice
            label: Tipo
            addFormOptions:
                empty_value: ''
                choices:
                    Tecnico: Soporte técnico
                    Comercial: Soporte comercial
builders:
    list:
        params:
            title: Tickets de soporte
            display: [ title, user, type, state]
            fields:
                user:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                new: ~
            object_actions:
                show: ~
                edit:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
                delete: ~   
    filters:
        params:
            display: [ type, state]
    new:
        params:
            title: Nuevo ticket
            display: [ title, type, description]
            credentials: 'hasRole("ROLE_FULL")'
            actions:
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el ticket \"%object%\"|{ %object%: Ticket.title }|"
            display: [ title, type, state, user, description]
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo el ticket \"%object%\"|{ %object%: Ticket.title }|"
            display: [ title, type, state, user, description]
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
