generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\User
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields:
        name:
            label: Nombre
        last_name:
            label: Apellido
        username:
            label: Usuario
        enabled: 
            label: Habilitado
        password:
            formType: password
            label: Contraseña
        emailable:
            label: Recibir Email?
            help: Si esta checkeado, recibira correos desde el sistema
          

builders:
    list:
        params:
            title: Usuarios
            display: [name, last_name, username, email, business, enabled]
            fields:
                business:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [username,email,enabled]
    new:
        params:
            title: Nuevo Usuario
            display: 
              NONE: [[name, last_name]]
              Usuario: [username, email, password, enabled, emailable]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando a usuario \"%object%\"|{ %object%: User.username }|"
            display: [name, last_name, username, email, password, enabled, emailable]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo \"%object%\"|{ %object%: User.username }|"
            display: [name, last_name, username, email, enabled, emailable]
            actions:
                list: ~
                new: ~
    delete: ~
