generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\User
    namespace_prefix: Trackme
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: BackendBundle
    fields:
        business:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            label: Cliente
        name:
            label: Nombre
        groups:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            label: Grupo
        last_name:
            label: Apellido
        username:
            label: Usuario
        enabled:
            label: Habilitado
        plainPassword:
            label:          Password
            dbType:         text
            formType:       repeated
            addFormOptions:
                first_options:
                    label:      Password
                second_options:
                    label:      Confirmar Password
                type:         password
        emailable:
            label: Recibir Email?
            help: Si esta checkeado, recibira correos desde el sistema
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Usuarios
            display: [name, last_name, username, email, business, enabled]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [username,email,enabled, business]
    new:
        params:
            title: Nuevo Usuario
            display:
              NONE: [[name, last_name, business]]
              Usuario: [username, email, groups, plainPassword, enabled, emailable]
            actions:
                save: ~
                save-and-add: ~
                list: ~
    edit:
        params:
            title: "Editando a usuario \"%object%\"|{ %object%: User.username }|"
            display:
                NONE: [[name, last_name, business]]
                Usuario: [username, email, groups, plainPassword, enabled, emailable]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viendo \"%object%\"|{ %object%: User.username }|"
            display: [name, last_name, username, email, enabled, emailable]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
