generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Vehicle
    namespace_prefix: Trackme
    bundle_name: BackendBundle
    fields:
        issues:
            label:            Mantenciones
            dbType:           collection
            formType:         collection
            addFormOptions:
                widget:         fieldset
                type:           \Trackme\BackendBundle\Form\Type\Mantention\EmbedType
                allow_add:      true
                allow_delete:   true
                by_reference:   false
                options:
                    label:          Nueva Mantencion
                    data_class:     Trackme\BackendBundle\Entity\VehicleMantention 
        code:
            label: Código
            help: Identificacion del vehiculo
        manufacturer:
            label: Marca
        model:
            label: Modelo
        kilometerPerLiter:
            label: Km/Litro
            formType: number
            addFormOptions:
                precision: 4
                attr:
                    placeholder: 10.5
        type:
            label: Tipo
            formType: choice
            addFormOptions:
                empty_value: ''
                choices:
                    Auto: Auto
                    Bus: Bus
                    Camión: Camión
                    Motocicleta: Moto
        fuel:  
            label: Combustible
            formType: choice  
            addFormOptions:
                empty_value: ''
                choices:
                    93: "93 Octanos"
                    95: "95 Octanos"
                    97: "97 Octanos"
                    Diesel: Diesel
                    Gas: Gas     

builders:
    list:
        params:
            title: Mis Vehiculos
            display: [ manufacturer, model, type, kilometerPerLiter ]
            fields:
                business:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            batch_actions:
                delete: ~        
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Nuevo Vehiculo
            display: 
                NONE: [ [manufacturer, model], [type, code, kilometerPerLiter], issues ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando Vehiculo \"%object%\"|{ %object%: Vehicle }|"
            display: 
                NONE: [ [manufacturer, model], [type, code, kilometerPerLiter], issues ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: Viendo
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
