generator: admingenerator.generator.doctrine
params:
    model: Trackme\BackendBundle\Entity\Vehicle
    namespace_prefix: Trackme
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: BackendBundle
    pk_requirement: ~
    fields:
        issues:
            label:            Mantenciones
            dbType:           collection
            formType:         collection
            addFormOptions:
                widget:         fieldset
                type:           \Trackme\BackendBundle\Form\Type\Mantention\EmbedType
                allow_add:      true
                allow_delete:   true
                by_reference:   false
                options:
                    label:          Nueva Mantencion
                    data_class:     Trackme\BackendBundle\Entity\VehicleMantention
        code:
            label: Código
            help: Identificacion del vehiculo
        manufacturer:
            label: Marca
        model:
            label: Modelo
        user:
            label: Conductor
            help: Usuario
        kilometerPerLiter:
            label: Km/Litro
            formType: number
            addFormOptions:
                precision: 4
                attr:
                    placeholder: 10.5
        type:
            label: Tipo
            formType: choice
            addFormOptions:
                empty_value: ''
                choices:
                    Auto: Auto
                    Bus: Bus
                    Camión: Camión
                    Motocicleta: Moto
        fuel:
            label: Combustible
            formType: choice
            addFormOptions:
                empty_value: ''
                choices:
                    93: "93 Octanos"
                    95: "95 Octanos"
                    97: "97 Octanos"
                    Diesel: Diesel
                    Gas: Gas
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            credentials: 'hasRole("ROLE_ADMIN") OR hasRole("ROLE_SUPER_ADMIN")'
            title: Mis Vehiculos
            display: [ code, manufacturer, model, type, kilometerPerLiter ]
            fields:
                business:
                    credentials: 'hasRole("ROLE_SUPER_ADMIN")'
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [ code, manufacturer, model, type, fuel ]
    new:
        params:
            credentials: 'hasRole("ROLE_ADMIN") OR hasRole("ROLE_SUPER_ADMIN")'
            title: Nuevo Vehiculo
            display:
                NONE: [ [user, manufacturer, model], [type, code, fuel, kilometerPerLiter], issues ]
            actions:
                save: ~
                save-and-add: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_ADMIN") OR hasRole("ROLE_SUPER_ADMIN")'
            title: "Editando Vehiculo \"%object%\"|{ %object%: Vehicle }|"
            display:
                NONE: [ [user, manufacturer, model], [type, code, fuel, kilometerPerLiter], issues ]
            actions:
                save: ~
                list: ~
    show:
        params:
            credentials: 'hasRole("ROLE_ADMIN") OR hasRole("ROLE_SUPER_ADMIN")'
            title: Viendo Vehiculo
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
